# Generated by Django 5.2.4 on 2025-08-21 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='errandrequest',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='errandrequest',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='errandrequest',
            name='runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_errands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='errandrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='errandrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='errandrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_errands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ErrandItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('grocery', 'Grocery'), ('document', 'Document'), ('package', 'Package'), ('other', 'Other')], default='other', max_length=50)),
                ('errand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='errands.errandrequest')),
            ],
        ),
    ]
