# Generated by Django 5.2.4 on 2025-08-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0002_errandrequest_dropoff_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erranditem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='errandrequest',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errandrequest',
            name='runner_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
