# Generated by Django 5.2.4 on 2025-08-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0005_errand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errandrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Errand',
        ),
    ]
