# Generated by Django 5.2.4 on 2025-08-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0007_errandrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erranditem',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Documents', 'Documents'), ('Packages', 'Packages'), ('Other', 'Other')], default='other', max_length=50),
        ),
    ]
