# Generated by Django 5.2.4 on 2025-08-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0008_alter_erranditem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erranditem',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('documents', 'Documents'), ('packages', 'Packages'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
